# Generated by Django 4.0.dev20210907181425 on 2021-09-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=20)),
                ('publicationDate', models.DateTimeField(verbose_name='publicationDate')),
                ('rollOver', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
    ]
